# Generated by Django 3.2.8 on 2021-10-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Branch name')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Starter/main/Desert/pizza...?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.branche')),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.foodtype'),
        ),
    ]
