# Generated by Django 3.2.8 on 2021-10-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0004_alter_foodtype_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branche',
        ),
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
