# Generated by Django 3.2.8 on 2021-10-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0005_auto_20211007_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Starter/main/Desert/pizza...?'),
        ),
    ]
