# Generated by Django 3.2.8 on 2021-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0006_alter_foodtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Number on the menu (optional)'),
        ),
    ]
