# Generated by Django 3.2.8 on 2021-10-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0007_foodtype_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Name')),
                ('visible', models.BooleanField(default=True, verbose_name='Can be showed on menu?')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Number on the menu (optional)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.branch')),
            ],
        ),
    ]
