# Generated by Django 3.2.8 on 2021-10-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0008_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.menu'),
        ),
    ]
