# Generated by Django 3.2.8 on 2021-10-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0009_alter_foodtype_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.menu', verbose_name='Menu and Branch'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.branch', verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chopchop.foodtype', verbose_name='Food type, Menu and Branch'),
        ),
    ]
