# Generated by Django 3.2.8 on 2021-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0010_auto_20211007_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
