# Generated by Django 3.2.8 on 2021-10-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0011_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
