# Generated by Django 3.2.8 on 2021-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0012_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='menu',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
    ]
