# Generated by Django 3.2.8 on 2021-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0013_auto_20211007_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='branch',
            name='picture',
            field=models.URLField(blank=True, default='', verbose_name='Picture Url'),
        ),
    ]
