# Generated by Django 3.2.8 on 2021-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0015_alter_branch_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='picture_url',
            field=models.TextField(blank=True, default='', verbose_name='Picture URL'),
        ),
    ]
