# Generated by Django 3.2.8 on 2021-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop', '0016_menuitem_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image_url', models.TextField(blank=True, default='', verbose_name='Header image URL')),
            ],
        ),
    ]
